"""empty message

Revision ID: 943f08b5e4ca
Revises: 39194341ac6d
Create Date: 2018-08-03 22:28:52.049103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943f08b5e4ca'
down_revision = '39194341ac6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_User__password', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', '_User__password')
    # ### end Alembic commands ###
